name: appbuild

on:
  push:
    tags:
      - "*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build Go
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/dist-about_amd64 .
          GOOS=linux GOARCH=arm64 go build -o dist/dist-about_arm64 .
          mv README.md dist/README.md
          mv LICENSE dist/LICENSE
          cd dist
          mv dist-about_amd64 dist-about
          zip dist-about_Linux_amd64 dist-about README.md LICENSE
          rm dist-about
          mv dist-about_arm64 dist-about
          zip dist-about_Linux_arm64 dist-about README.md LICENSE
      - uses: actions/upload-artifact@v3
        with:
          name: Binalys
          path: dist/*.zip
